title: Babun
description: A windows shell you will love!
author: Babun Team
#disqus: asciidoctor
#disqus_generate_id: true
#disqus_developer: true
haml:
  :ugly: true
asciidoctor:
  :eruby: erubis
  :attributes:
    idprefix: ''
    idseparator: '-'
    icons: 'font'
    sectanchors: ''
    linkattrs: ''
    source-highlighter: coderay
    'prewrap!': ''
# if no profile is specified, the first with a deploy config is selected
profiles:
  development:
    deploy: nil
  staging:
    deploy: nil
  production:
    base_url: http://babun.guthub.io
    #disqus_developer: false
    #google_analytics: UA-38215684-1
    compass_output_style: :compressed
    deploy:
      host: babun.github.io
      branch: master
